### ISSUE TITLE
previous portfolio

### ISSUE THREAD

**Issue by PrakasRavichandran** [AKR0SS/akr0ss.github.io#5]
What about your previous portfolio website? I took 2 hours of searching to find your GitHub account to view your previous portfolio. But there is a different portfolio 😢. 

mail ID: prakashravichandran253@gmail.com

**Comment by akrossu** [comment]
I have two previous portfolios if you'd be interested under the two archived branches in this repo here:
- https://github.com/AKR0SS/akr0ss.github.io/tree/archive
- https://github.com/AKR0SS/akr0ss.github.io/tree/rewrite
